import json
import pandas as pd
import os

# Paths (generated by the test script)
json_path = os.path.join('test_simulated_data', 'pixel_color_matrix_category_basedmarkersize60_clusternumber2_datanumber500_testnumbercategorymedium_repeatnumber1.json')
csv_path = os.path.join('test_simulated_data', 'analysis_data_category_basedmarkersize60_clusternumber2_datanumber500_testnumbercategorymedium_repeatnumber1.csv')

if not os.path.exists(json_path):
    print('JSON file not found:', json_path)
    raise SystemExit(1)
if not os.path.exists(csv_path):
    print('CSV file not found:', csv_path)
    raise SystemExit(1)

with open(json_path, 'r') as f:
    matrix = json.load(f)

# Load dataframe to map ID -> class
df = pd.read_csv(csv_path)
if 'ID' not in df.columns:
    raise SystemExit('CSV does not contain ID column')
if 'class' not in df.columns:
    raise SystemExit('CSV does not contain class column')

id_to_class = dict(zip(df['ID'], df['class']))

# Prepare per-ID bookkeeping
from collections import defaultdict
pixels_per_id = defaultdict(set)
any_pixel_top_diff = defaultdict(bool)
all_pixels_top_diff = defaultdict(lambda: True)
any_pixel_visible = defaultdict(bool)

H = len(matrix)
W = len(matrix[0]) if H>0 else 0

for y in range(H):
    for x in range(W):
        stack = matrix[y][x]
        if not stack:
            continue
        # topmost entry
        top = stack[-1]
        top_cat = None
        top_id = None
        if isinstance(top, dict):
            top_cat = top.get('category')
            top_id = top.get('ID')
        # For each element in stack, if it has an ID, record the pixel
        for elem in stack:
            if not isinstance(elem, dict):
                continue
            eid = elem.get('ID')
            if eid is None:
                continue
            pixels_per_id[eid].add((x,y))
            # if top category exists and differs from this element's class, mark any_pixel_top_diff
            if top_cat is not None:
                if top_cat != id_to_class.get(eid):
                    any_pixel_top_diff[eid] = True
                else:
                    # if top category equals element class then not all pixels are top-different
                    all_pixels_top_diff[eid] = False
            else:
                # cannot determine top category -> treat as not different
                all_pixels_top_diff[eid] = False
            # if topmost is this element, it's visible at least somewhere
            if top_id == eid:
                any_pixel_visible[eid] = True
                all_pixels_top_diff[eid] = False

# Compute metrics
ids = sorted(id_to_class.keys())
ids_with_pixels = [i for i in ids if i in pixels_per_id and len(pixels_per_id[i])>0]

num_with_any_pixel_covered_by_diff = sum(1 for i in ids_with_pixels if any_pixel_top_diff[i])
num_fully_covered_by_diff = sum(1 for i in ids_with_pixels if all_pixels_top_diff[i])
num_ids_with_no_pixels = sum(1 for i in ids if i not in pixels_per_id or len(pixels_per_id[i])==0)

print('Total number of data IDs in CSV:', len(ids))
print('Number of IDs that have at least one pixel in the matrix:', len(ids_with_pixels))
print('Number of IDs with no pixels mapped (unexpected):', num_ids_with_no_pixels)
print('Number of distinct data IDs that have at least one pixel where the topmost category differs from their class:', num_with_any_pixel_covered_by_diff)
print('Number of distinct data IDs that are fully covered (all their pixels) by a different class topmost:', num_fully_covered_by_diff)

# Optionally print some examples
examples_any = [i for i in ids_with_pixels if any_pixel_top_diff[i]][:10]
examples_full = [i for i in ids_with_pixels if all_pixels_top_diff[i]][:10]
print('Examples (IDs) with any differing-top pixels:', examples_any)
print('Examples (IDs) fully covered by different class (examples):', examples_full)

# Also compute number of pixels covered by different category (simple count where any lower differs)
pixel_count_any_diff = 0
pixel_count_importance_condition = 0
for y in range(H):
    for x in range(W):
        stack = matrix[y][x]
        if not stack or len(stack) < 2:
            continue
        top = stack[-1]
        if not isinstance(top, dict):
            continue
        top_imp = top.get('importance_value', None)
        top_cat = top.get('category')
        for elem in stack[:-1]:
            if not isinstance(elem, dict):
                continue
            if elem.get('category') != top_cat:
                pixel_count_any_diff += 1
                # check importance condition
                if elem.get('importance_value') is not None and top_imp is not None and elem.get('importance_value') > top_imp:
                    pixel_count_importance_condition += 1
                break

print('Number of pixels where at least one lower element has different category:', pixel_count_any_diff)
print('Number of pixels where a lower element has different category AND higher importance than top:', pixel_count_importance_condition)
